### PR TITLE
Added messages

### PR DESCRIPTION
**Pull request by ghost**
Added sensible default messages to assertion functions.

### CODE REVIEW

**Comment by emilbayes** [comment]
Hi! Thank you for your contribution, but I don't want to have default messages, but rather encourage messages to be set. However I do agree that the stack trace that one gets right now is not very informative as the error originates from nanoassert and not the site of the assertion

**Comment by ghost** [comment]
@emilbayes This follows Chai and other libraries. You might have tried out Chai and seen something like this:

```txt
AssertionError: Expected "0" to equal "1".
+ expected
- actual

- 0
+ 1
```

I admit this is nothing close to that, but I think default messages should be added for users that are in a hurry - take me for example, I'd rather be working on tests instead of writing messages that the library could do for me. If I was using this for my testing, I would have sent this PR a long time ago, because seeing errors like:

```txt
AssertionError

at (...)
at (...)
at (...)
at (...)
...

is not at all helpful to me, and it gives no hint as to why the assertion failed.  As said before, users should be given sensible default assertion error messages to save them time. Isn't that the point of using a library in the first place?

**Comment by emilbayes** [comment]
I will fix the stack trace, but if users are lazy, they're lazy. I think the "AssertionError" message is more than enough to say that something catastrophic happened :)

**Comment by ghost** [comment]
@emilbayes I disagree. How is it being lazy? As I said before, I'd much rather be working on the app than assertion messages **that the library *should* provide**. I don't get why this is an issue, as it's just a few more bytes which is nothing, and it saves you writing assertion messages, *and* if you want this library to be a drop-in replacement for "assert" then you need to provide this stuff. Users expect it.

**Pull request closed without merging**
