### PR TITLE
Fixed tape not running tests

### PR DESCRIPTION
**Pull request by ghost**
Apparently tape prefers it when you manually add ".js" onto the name of
the test file you pass to the CLI. I have fixed this issue in this commit.

### CODE REVIEW

**Comment by emilbayes** [comment]
Thanks! Can you change just the tape version and the test script?

**Comment by ghost** [comment]
The test script is what fixes the issue.

**Comment by ghost** [comment]
@emilbayes You gonna pull this? It fixes a pretty big issue.

**Comment by emilbayes** [comment]
Not with the package lock file and the reordering of the package.json. Otherwise I appreciate the effort very much

**Comment by def14nt** [comment]
Wow it really matters if it's reordered lol.

**Comment by def14nt** [comment]
You just really don't wanna merge this do you lol

**Pull request closed without merging**
