### PR TITLE
add more methods, remove dft message

### PR DESCRIPTION
**Pull request by yoshuawuyts**
Wanted to write this module, but saw you'd already written it haha. This PR contains a few changes; most notably:

- added `.equal`, `.ok`, `.notEqual`, and `.notOk` methods
- removed the default message

The reasoning to add more methods is because those are the methods we use all throughout the choo codebase / ecosystem. I'm planning to write a browserify transform to dynamically replace them with this module, which should make for some really cool results.

The default message was removed because strings don't compress well, and if people are going to be including custom messages everywhere anyway it's just dead code anyway.

Hope this PR makes sense; thanks! :D

### CODE REVIEW

**Comment by emilbayes** [comment]
I will accept the additions but want to keep the default message. If you use any kind of compression the string will most likely compress too and it's only a few bytes.

A question: does it matter whether the other methods are set on `assert` or `exports`? Like:
```js
module.exports = assert
function assert (t, m) {
  if (!t) throw new Error(m)
}

exports.ok = assert

exports.equal = function (a, b, m) {
  assert(a == b, m) // eslint-disable-line eqeqeq
}

exports.notEqual = function (a, b, m) {
  assert(a != b, m) // eslint-disable-line eqeqeq
}

exports.notOk = function (t, m) {
  assert(!t, m)
}
```

**Comment by yoshuawuyts** [comment]
Restored the default error message :sparkles: - tried a variation of your suggestion and couldn't get the code to work; think just setting the value on `assert` is generally a good pattern as it prevents a whole class of scoping gotchas (:

**Comment by emilbayes** [comment]
Released as `1.1.0`

**Comment by yoshuawuyts** [comment]
woot! :D

**Pull request merged**
